config/routes.rb
Hw4::Application.routes.draw do

  resources :subsubtopic_values

  resources :subtopic_values

  resources :topic_values

  resources :evaluations do
    resources :topic_values
  end
  
  resources :subtopics do
    resources :subsubtopics
  end
   
  resources :subtopics do
    resources :subtopics
  end
  
  resources :topics do
    resources :subtopics
  end

  resources :skeletons do
    resources :topics do
      resources :subtopics do
        resources :subsubtopics
      end
    end
  end
	
	 

end

app/models/subsubtopic_value.rb
class SubsubtopicValue < ActiveRecord::Base
end

app/controllers/subsubtopic_values_controller.rb
class SubsubtopicValuesController < ApplicationController
  # GET /subsubtopic_values
  # GET /subsubtopic_values.xml
  def index
    @subsubtopic_values = SubsubtopicValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subsubtopic_values }
    end
  end

  # GET /subsubtopic_values/1
  # GET /subsubtopic_values/1.xml
  def show
    @subsubtopic_value = SubsubtopicValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subsubtopic_value }
    end
  end

  # GET /subsubtopic_values/new
  # GET /subsubtopic_values/new.xml
  def new
    @subsubtopic_value = SubsubtopicValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subsubtopic_value }
    end
  end

  # GET /subsubtopic_values/1/edit
  def edit
    @subsubtopic_value = SubsubtopicValue.find(params[:id])
  end

  # POST /subsubtopic_values
  # POST /subsubtopic_values.xml
  def create
    @subsubtopic_value = SubsubtopicValue.new(params[:subsubtopic_value])

    respond_to do |format|
      if @subsubtopic_value.save
        format.html { redirect_to(@subsubtopic_value, :notice => 'Subsubtopic value was successfully created.') }
        format.xml  { render :xml => @subsubtopic_value, :status => :created, :location => @subsubtopic_value }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subsubtopic_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subsubtopic_values/1
  # PUT /subsubtopic_values/1.xml
  def update
    @subsubtopic_value = SubsubtopicValue.find(params[:id])

    respond_to do |format|
      if @subsubtopic_value.update_attributes(params[:subsubtopic_value])
        format.html { redirect_to(@subsubtopic_value, :notice => 'Subsubtopic value was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subsubtopic_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subsubtopic_values/1
  # DELETE /subsubtopic_values/1.xml
  def destroy
    @subsubtopic_value = SubsubtopicValue.find(params[:id])
    @subsubtopic_value.destroy

    respond_to do |format|
      format.html { redirect_to(subsubtopic_values_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/subsubtopic_values_helper.rb
module SubsubtopicValuesHelper
end

app/views/subsubtopic_values/_form.html.erb
<%= form_for(@subsubtopic_value) do |f| %>
  <% if @subsubtopic_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subsubtopic_value.errors.count, "error") %> prohibited this subsubtopic_value from being saved:</h2>

      <ul>
      <% @subsubtopic_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evaluation_id %><br />
    <%= f.text_field :evaluation_id %>
  </div>
  <div class="field">
    <%= f.label :subsubtopic_id %><br />
    <%= f.text_field :subsubtopic_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subsubtopic_values/edit.html.erb
<h1>Editing subsubtopic_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @subsubtopic_value %> |
<%= link_to 'Back', subsubtopic_values_path %>

app/views/subsubtopic_values/index.html.erb
<h1>Listing subsubtopic_values</h1>

<table>
  <tr>
    <th>Evaluation</th>
    <th>Subsubtopic</th>
    <th>Value</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subsubtopic_values.each do |subsubtopic_value| %>
  <tr>
    <td><%= subsubtopic_value.evaluation_id %></td>
    <td><%= subsubtopic_value.subsubtopic_id %></td>
    <td><%= subsubtopic_value.value %></td>
    <td><%= subsubtopic_value.comments %></td>
    <td><%= link_to 'Show', subsubtopic_value %></td>
    <td><%= link_to 'Edit', edit_subsubtopic_value_path(subsubtopic_value) %></td>
    <td><%= link_to 'Destroy', subsubtopic_value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subsubtopic value', new_subsubtopic_value_path %>

app/views/subsubtopic_values/new.html.erb
<h1>New subsubtopic_value</h1>

<%= render 'form' %>

<%= link_to 'Back', subsubtopic_values_path %>

app/views/subsubtopic_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Evaluation:</b>
  <%= @subsubtopic_value.evaluation_id %>
</p>

<p>
  <b>Subsubtopic:</b>
  <%= @subsubtopic_value.subsubtopic_id %>
</p>

<p>
  <b>Value:</b>
  <%= @subsubtopic_value.value %>
</p>

<p>
  <b>Comments:</b>
  <%= @subsubtopic_value.comments %>
</p>


<%= link_to 'Edit', edit_subsubtopic_value_path(@subsubtopic_value) %> |
<%= link_to 'Back', subsubtopic_values_path %>