config/routes.rb
Hw4::Application.routes.draw do

  resources :subsubtopic_values

  resources :subtopic_values

  resources :topic_values

  resources :evaluations do
    resources :topic_values
  end
  
  resources :subtopics do
    resources :subsubtopics
  end
   
  resources :subtopics do
    resources :subtopics
  end
  
  resources :topics do
    resources :subtopics
  end

  resources :skeletons do
    resources :topics do
      resources :subtopics do
        resources :subsubtopics
      end
    end
  end
	
	 

end

app/models/skeleton.rb
class Skeleton < ActiveRecord::Base
  has_many :topics
  has_many :evaluations
  validates :name, :presence => true
end

app/controllers/skeletons_controller.rb
class SkeletonsController < ApplicationController
  # GET /skeletons
  # GET /skeletons.xml
  
  before_filter :authenticate, :except => [:index, :show]
  
  def index
    @skeletons = Skeleton.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @skeletons }
    end
  end

  # GET /skeletons/1
  # GET /skeletons/1.xml
  def show
    @skeleton = Skeleton.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @skeleton }
    end
  end

  # GET /skeletons/new
  # GET /skeletons/new.xml
  def new
    @skeleton = Skeleton.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @skeleton }
    end
  end

  # GET /skeletons/1/edit
  def edit
    @skeleton = Skeleton.find(params[:id])
  end

  # POST /skeletons
  # POST /skeletons.xml
  def create
    @skeleton = Skeleton.new(params[:skeleton])

    respond_to do |format|
      if @skeleton.save
        format.html { redirect_to(@skeleton, :notice => 'Skeleton was successfully created.') }
        format.xml  { render :xml => @skeleton, :status => :created, :location => @skeleton }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @skeleton.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /skeletons/1
  # PUT /skeletons/1.xml
  def update
    @skeleton = Skeleton.find(params[:id])

    respond_to do |format|
      if @skeleton.update_attributes(params[:skeleton])
        format.html { redirect_to(@skeleton, :notice => 'Skeleton was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @skeleton.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /skeletons/1
  # DELETE /skeletons/1.xml
  def destroy
    @skeleton = Skeleton.find(params[:id])
    @skeleton.destroy

    respond_to do |format|
      format.html { redirect_to(skeletons_url) }
      format.xml  { head :ok }
    end
  end


 private
 
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "admin"
    end
  end

end

app/helpers/skeletons_helper.rb
module SkeletonsHelper
end

app/views/skeletons/_form.html.erb
<%= form_for(@skeleton) do |f| %>
  <% if @skeleton.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skeleton.errors.count, "error") %> prohibited this skeleton from being saved:</h2>

      <ul>
      <% @skeleton.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skeletons/_skeleton.html.erb
<h1> <%= @skeleton.name %></h1>
  

app/views/skeletons/edit.html.erb
<h1>Editing skeleton</h1>

<%= render 'form' %>

<%= link_to 'Show', @skeleton %> |
<%= link_to 'Back', skeletons_path %>

app/views/skeletons/index.html.erb
<h1>Listing skeletons</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skeletons.each do |skeleton| %>
  <tr>
    <td><%= skeleton.name %></td>
    <td><%= link_to 'Show', skeleton %></td>
    <td><%= link_to 'Edit', edit_skeleton_path(skeleton) %></td>
    <td><%= link_to 'Destroy', skeleton, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skeleton', new_skeleton_path %>

app/views/skeletons/new.html.erb
<h1>New skeleton</h1>

<%= render 'form' %>

<%= link_to 'Back', skeletons_path %>

app/views/skeletons/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => @skeleton%>
  
  <table border="1">
    <div id="topics">
      <% @skeleton.topics.each do |topic| %>
      <% div_for topic do %>
      <tr bgcolor="#666666">
        <div id="topic" >
        <th> <a href="<%= @skeleton.id%>/topics/<%= topic.id%>"><%= topic.name%></th>
        <th> <%= topic.description%></th>
        <th> <%= topic.range%></th>   
        </div>
      </tr>
        <% topic.subtopics.each do |subtopic| %>
          <% div_for subtopic do %>
          <tr bgcolor="#AAAAAA">
          <div id="subtopic">
            <td> <%= h(subtopic.name)%></td>
            <td> <%= h(subtopic.description)%></td>
            <td> <%= h(subtopic.range)%></td> 
          </div>
          </tr>
             <% subtopic.subsubtopics.each do |subsubtopic| %>
              <% div_for subsubtopic do %>
               <tr bgcolor="#DDDDDD">
                <div id="subsubtopic">
                  <td> -<%= h(subsubtopic.name)%></td>
                  <td> <%= h(subsubtopic.description)%></td>
                  <td> <%= h(subsubtopic.range)%></td> 
                </div>
               </tr>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% end %>
</div>
</table>

<p>New Topic
<table>
      <% form_for [@skeleton, Topic.new], do |f| %>
        <tr>
          <td><%= f.label :name, "Name" %></td>
          <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :description, "Description" %></td>
            <td><%= f.text_field :description %></td>
          </tr>
          <tr>
            <td><%= f.label :range, "Range(number of levels)" %></td>
            <td><%= f.text_field :range %></td>
        </tr>
        <tr>
        <td></td><td><%= f.submit "Add Topic" %></td></tr>
      <% end %>
</table>
</p>

<p>
<%= link_to 'Edit', edit_skeleton_path(@skeleton) %> |
<%= link_to 'Back', skeletons_path %>
</p>