config/routes.rb
Hw4::Application.routes.draw do

  resources :subsubtopic_values

  resources :subtopic_values

  resources :topic_values

  resources :evaluations do
    resources :topic_values
  end
  
  resources :subtopics do
    resources :subsubtopics
  end
   
  resources :subtopics do
    resources :subtopics
  end
  
  resources :topics do
    resources :subtopics
  end

  resources :skeletons do
    resources :topics do
      resources :subtopics do
        resources :subsubtopics
      end
    end
  end
	
	 

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :skeleton
  has_many :subtopics
  validates :name, :presence => true
  validates :skeleton_id, :presence => true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.xml
  
  before_filter :authenticate, :except => [:index, :show]
  
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
      @skeleton=Skeleton.find(params[:skeleton_id])
      @topic = @skeleton.topics.create(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to(@skeleton)}
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
  
 private
 
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "admin"
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :range %><br />
    <%= f.text_field :range %>
  </div>
  <div class="field">
    <%= f.label :skeleton_id %><br />
    <%= f.text_field :skeleton_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<tr  bgcolor="#666666">  
    <th><%= @topic.name %> </th>
    <th><%= @topic.description %> </th>
    <th><%= @topic.range %> </th>
</tr>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Range</th>
    <th>Skeleton</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.name %></td>
    <td><%= topic.description %></td>
    <td><%= topic.range %></td>
    <td><%= topic.skeleton_id %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Topic: <%= @topic.name %></h2>
<table border="1">
  <tr  bgcolor="#666666">  
    <th><%= @topic.name %> </th>
    <th><%= @topic.description %> </th>
    <th><%= @topic.range %> </th>
   </tr>
   <% @topic.subtopics.each do |subtopic| %>
    <% div_for subtopic do %>
    <tr bgcolor="#AAAAAA">
      <div id="subtopic">
        <td> <a href="<%= @topic.id%>/subtopics/<%= subtopic.id%>"><%= h(subtopic.name)%></td>
        <td> <%= h(subtopic.description)%></td>
        <td> <%= h(subtopic.range)%></td> 
      </div>
    </tr>
    <% subtopic.subsubtopics.each do |subsubtopic| %>
              <% div_for subsubtopic do %>
               <tr bgcolor="#DDDDDD">
                <div id="subsubtopic">
                  <td> -<%= h(subsubtopic.name)%></td>
                  <td> <%= h(subsubtopic.description)%></td>
                  <td> <%= h(subsubtopic.range)%></td> 
                </div>
               </tr>
              <% end %>
            <% end %>
    <% end %>
  <% end %>
 </table>

<p>New Subtopic
<table>
      <% form_for [@topic, Subtopic.new] do |f| %>
        <tr>
          <td><%= f.label :name, "Name" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :description, "Description" %></td>
          <td><%= f.text_field :description %></td>
        </tr>
        <tr>
          <td><%= f.label :range, "Range(number of levels)" %></td>
          <td><%= f.text_field :range %></td>
        </tr>
        <tr>
        <td></td><td><%= f.submit "Add Subtopic" %></td></tr>
      <% end %>
</table>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>