config/routes.rb
Hw4::Application.routes.draw do

  resources :subsubtopic_values

  resources :subtopic_values

  resources :topic_values

  resources :evaluations do
    resources :topic_values
  end
  
  resources :subtopics do
    resources :subsubtopics
  end
   
  resources :subtopics do
    resources :subtopics
  end
  
  resources :topics do
    resources :subtopics
  end

  resources :skeletons do
    resources :topics do
      resources :subtopics do
        resources :subsubtopics
      end
    end
  end
	
	 

end

app/models/topic_value.rb
class TopicValue < ActiveRecord::Base
end

app/controllers/topic_values_controller.rb
class TopicValuesController < ApplicationController
  # GET /topic_values
  # GET /topic_values.xml
  def index
    @topic_values = TopicValue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topic_values }
    end
  end

  # GET /topic_values/1
  # GET /topic_values/1.xml
  def show
    @topic_value = TopicValue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic_value }
    end
  end

  # GET /topic_values/new
  # GET /topic_values/new.xml
  def new
    @topic_value = TopicValue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic_value }
    end
  end

  # GET /topic_values/1/edit
  def edit
    @topic_value = TopicValue.find(params[:id])
  end

  # POST /topic_values
  # POST /topic_values.xml
def create
    @evaluation = Evaluation.find(params[:evaluation_id])
    found=false;
    
    topics = @evaluation.topic_values
    topics.each do |t|
      if t.topic_id == params[:topic_id]
        found=true;
        @topic_value=t;
      end
    end

    if not found
      @topic_value = @evaluation.topic_values.create!(params[:topic_value])
      respond_to do |format|
        if @topic_value.save
          format.html { redirect_to(@evaluation) }
          format.xml  { render :xml => @topic_value, :status => :created, :location => @topic_value }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @topic_value.errors, :status => :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @topic_value.update_attributes(params[:topic_value])
          format.html { redirect_to(@evaluation) }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @topic_value.errors, :status => :unprocessable_entity }
        end
      end
    end
    
  end

  # PUT /topic_values/1
  # PUT /topic_values/1.xml
  def update
    @topic_value = TopicValue.find(params[:id])

    respond_to do |format|
      if @topic_value.update_attributes(params[:topic_value])
        format.html { redirect_to(@topic_value, :notice => 'Topic value was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic_value.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topic_values/1
  # DELETE /topic_values/1.xml
  def destroy
    @topic_value = TopicValue.find(params[:id])
    @topic_value.destroy

    respond_to do |format|
      format.html { redirect_to(topic_values_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/topic_values_helper.rb
module TopicValuesHelper
end

app/views/topic_values/_form.html.erb
<%= form_for(@topic_value) do |f| %>
  <% if @topic_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic_value.errors.count, "error") %> prohibited this topic_value from being saved:</h2>

      <ul>
      <% @topic_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :evaluation_id %><br />
    <%= f.text_field :evaluation_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.text_field :topic_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topic_values/edit.html.erb
<h1>Editing topic_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic_value %> |
<%= link_to 'Back', topic_values_path %>

app/views/topic_values/index.html.erb
<h1>Listing topic_values</h1>

<table>
  <tr>
    <th>Evaluation</th>
    <th>Topic</th>
    <th>Value</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topic_values.each do |topic_value| %>
  <tr>
    <td><%= topic_value.evaluation_id %></td>
    <td><%= topic_value.topic_id %></td>
    <td><%= topic_value.value %></td>
    <td><%= topic_value.comments %></td>
    <td><%= link_to 'Show', topic_value %></td>
    <td><%= link_to 'Edit', edit_topic_value_path(topic_value) %></td>
    <td><%= link_to 'Destroy', topic_value, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic value', new_topic_value_path %>

app/views/topic_values/new.html.erb
<h1>New topic_value</h1>

<%= render 'form' %>

<%= link_to 'Back', topic_values_path %>

app/views/topic_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Evaluation:</b>
  <%= @topic_value.evaluation_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @topic_value.topic_id %>
</p>

<p>
  <b>Value:</b>
  <%= @topic_value.value %>
</p>

<p>
  <b>Comments:</b>
  <%= @topic_value.comments %>
</p>


<%= link_to 'Edit', edit_topic_value_path(@topic_value) %> |
<%= link_to 'Back', topic_values_path %>